import subprocess
import json

subjects = [
    ('mta_dispatcher_decisions-value', 'In-Stream AI Dispatcher Decisions (Output of Flink AI_RUN_AGENT & source for HTTP Sink Connector)'),
    ('mta_headway_alerts-value', 'Headway Bunching & Gap Alerts (Output of Flink CEP MATCH_RECOGNIZE)'),
    ('mta_headway_forecast-value', 'Headway Predictive Forecast (CEP Predictive Headway Trends)'),
    ('mta_passenger_surges-value', 'Passenger Turnstile Crowd Surges (Generated by DatagenSource Connector)'),
    ('nyc_weather_events-value', 'Live NYC Weather Observations (Ingested by HttpSource Connector from Open-Meteo)'),
    ('mta_service_alerts-value', 'MTA Real-Time Service Alerts (Ingested by HttpSource Connector from NY Open Data)'),
    ('mta_arrival_estimates-value', 'Live Station Arrival Estimates (Computed by Flink SQL continuous queries)'),
    ('mta_vehicle_positions-value', 'Subway Train Vehicle Positions (Ingested from GTFS-RT protobuf)'),
    ('mta_trip_updates-value', 'Subway Train Trip Updates (Ingested from GTFS-RT protobuf)'),
    ('mta_bus_positions-value', 'MTA Bus Vehicle Positions (~2,700 live buses with GPS & heading)'),
    ('mta_bus_corridor_speed-value', 'Bus Corridor Congestion & Velocity Analytics (Computed by Flink 10_bus_congestion.sql window aggregation)'),
    ('mta_weather_impact_alerts-value', 'Weather-Impact Enriched Headway Alerts (Computed by Flink 11_weather_impact.sql joining alerts with weather)'),
    ('mta_station_bottlenecks-value', 'Multi-Modal Station Bottlenecks (Computed by Flink 12_station_bottlenecks.sql joining surges with headway alerts)')
]

doc = """# Transit Pulse NYC — Confluent Schema Registry Schemas

This document contains all active schemas registered in **Confluent Cloud Schema Registry** for the Transit Pulse NYC streaming intelligence platform.

| Subject | Schema ID | Format | Description |
|---|---|---|---|
"""

entries = []
for s, desc in subjects:
    res = subprocess.run(['confluent', 'schema-registry', 'schema', 'describe', '--subject', s, '--version', 'latest'], capture_output=True, text=True)
    out = res.stdout
    schema_id = 'Unknown'
    schema_type = 'AVRO'
    schema_body = ''
    for line in out.splitlines():
        if line.startswith('Schema ID:'):
            schema_id = line.split(':', 1)[1].strip()
        elif line.startswith('Type:'):
            schema_type = line.split(':', 1)[1].strip()
    if 'Schema:' in out:
        schema_body = out.split('Schema:', 1)[1].strip()
    entries.append((s, desc, schema_id, schema_type, schema_body))
    doc += f"| `{s}` | `{schema_id}` | `{schema_type}` | {desc} |\n"

doc += "\n---\n\n"

for s, desc, schema_id, schema_type, schema_body in entries:
    doc += f"## {s}\n\n"
    doc += f"- **Description**: {desc}\n"
    doc += f"- **Schema ID**: `{schema_id}`\n"
    doc += f"- **Format**: `{schema_type}`\n\n"
    doc += f"```json\n{schema_body}\n```\n\n---\n\n"

with open('docs/SCHEMAS.md', 'w') as f:
    f.write(doc)

print("Generated docs/SCHEMAS.md successfully. Size:", len(doc))
